const _ = require('lodash')
exports.lodash_helper = {
  invert: _.invert,
  findIndex: _.findIndex,
  isInteger: _.isInteger,
  groupBy: _.groupBy,
  inRange: _.inRange,
  clamp: _.clamp,
  min: _.min,
  max: _.max,
  remove: _.remove,
  sumBy: _.sumBy,
  mapKeys: _.mapKeys,
  toPairs: _.toPairs,
  isEqual: _.isEqual,
  toNumber: _.toNumber,
  isPlainObject: _.isPlainObject,
  map: _.map,
  orderBy: _.orderBy,
  debounce: _.debounce,
  maxBy: _.maxBy,
  isArray: _.isArray,
  merge: _.merge,
  isObject: _.isObject,
  isObjectLike: _.isObjectLike,
  keys: _.keys,
  values: _.values,
  throttle: _.throttle,
  random: _.random,
  has: _.has,
  get: _.get,
  set: _.set,
  isNil: _.isNil,
  isEmpty: _.isEmpty,
  isNull: _.isNull,
  isNaN: _.isNaN,
  isUndefined: _.isUndefined,
  isBoolean: _.isBoolean,
  isNumber: _.isNumber,
  isString: _.isString,
  cloneDeep: _.cloneDeep,
  uniqueId: _.uniqueId,
  isFunction: _.isFunction
}

